[package]
name = "tradeassembly-xtask"
version = "0.1.0"
edition = "2021"
publish = false
license-file = "../LICENSE"

[dependencies]
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
glob = "0.3"
globset = "0.4"
libc = "0.2"
tradeassembly-runtime = { path = "../runtime-rs" }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
sha2 = "0.10"
tar = "0.4"
tempfile = "3"
walkdir = "2"
