// Copyright (c) 2026 OptionLab LLC. All rights reserved.

pub fn cli_command_inventory() -> Vec<&'static str> {
    vec![
        "agent install",
        "agent status",
        "agent uninstall",
        "agent verify",
        "account login",
        "account status",
        "api",
        "attribution-journal export",
        "attribution-journal inspect",
        "attribution-journal replay",
        "attribution-journal report",
        "attribution-journal review",
        "backtest",
        "dataset-ingestion cancel",
        "dataset-ingestion create",
        "dataset-ingestion get",
        "dataset-ingestion list",
        "dataset-ingestion status",
        "dataset-ingestion verify",
        "credentials status",
        "credentials test",
        "demo",
        "demos list",
        "demos run",
        "events publish",
        "events pull",
        "execution activate",
        "execution config-save",
        "execution control",
        "execution deactivate",
        "execution readiness",
        "execution run",
        "execution status",
        "fill-quality export",
        "fill-quality inspect",
        "fill-quality replay",
        "fill-quality report",
        "instruments aliases",
        "instruments pack-status",
        "instruments resolve",
        "install claim",
        "lifecycle import",
        "lifecycle inspect",
        "lifecycle replay",
        "lifecycle status",
        "lifecycle-calendar export",
        "lifecycle-calendar inspect",
        "lifecycle-calendar list",
        "lifecycle-calendar replay",
        "marketdata bars",
        "marketdata indicators",
        "marketdata option-chain",
        "marketdata option-select",
        "marketdata quote",
        "mcp serve",
        "monte-carlo export",
        "monte-carlo replay",
        "monte-carlo report",
        "monte-carlo run",
        "monte-carlo status",
        "options chain",
        "options select",
        "orders attempts",
        "orders reconcile",
        "plugins disable",
        "plugins install",
        "plugins invoke",
        "plugins status",
        "positions",
        "providers credential-status",
        "providers credential-test",
        "providers list",
        "providers policy",
        "readiness",
        "replay",
        "report",
        "report-envelope",
        "research jobs",
        "research sweep",
        "research universe",
        "research-notebook attach",
        "research-notebook compose",
        "research-notebook create",
        "research-notebook export",
        "research-notebook inspect",
        "research-notebook list",
        "research-notebook replay",
        "reset",
        "reset-btc-demo",
        "risk account-set",
        "risk overlay",
        "risk status",
        "risk stress",
        "scheduler run",
        "scheduler start",
        "scheduler status",
        "scheduler stop",
        "scenario valuation",
        "seed",
        "seed-btc-demo",
        "selectors evaluate",
        "selectors explain",
        "strategy create",
        "strategy get",
        "strategy list",
        "strategy validate",
        "telemetry emit",
        "telemetry opt-out",
        "telemetry replay",
        "workers run",
        "workers status",
    ]
}
